services:
  - type: web
    name: bouda-tech-app
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bouda-tech-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CRON_SECRET
        generateValue: true
      - key: PAYMENT_MODE
        value: sandbox
      - key: EMAIL_MODE
        value: sandbox
      - key: EMAIL_FROM
        value: "BOUDA-TECH <no-reply@bouda-tech.bf>"
      - key: CONTACT_EMAIL_TO
        value: ernestbouda@yahoo.fr
      - key: SMS_MODE
        value: sandbox
      - key: NEXT_PUBLIC_SITE_URL
        value: https://bouda-tech-app.onrender.com

databases:
  - name: bouda-tech-db
    plan: free
